baseURL = "https://Cola1605.github.io/System_News/"
title = "Blog của Khoa"
languageCode = "vi"
theme = "Mainroad"

[params]
  description = "Blog cá nhân chia sẻ kiến thức về lập trình, AI và công nghệ."
  author = "Cola1605"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
