baseURL = "https://cola1605.github.io"
title = "SYSTEM_NEWS"
languageCode = "vi"

theme = ""
disqusShortname = ""
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  
[Author]
  name = "Cola1605"
  bio = "Chuyên gia về AI, lập trình và công nghệ. Chia sẻ kiến thức và kinh nghiệm thực tế."
  avatar = "img/avatar.png"

[Params]
  description = "Blog cá nhân chia sẻ kiến thức về lập trình, AI và công nghệ."
  opengraph = true
  twitter_cards = false
  readmore = true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["posts"]

[Params.logo]
  subtitle = "AI & Technology Blog"

[Params.sidebar]
  home = "right"
  list = "right"  
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "archive"]

[Params.widgets]
  recent_num = 5
  tags_counter = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[markup.highlight]
  style = "github"
  lineNos = true
  lineNumbersInTable = false
  
[pagination]
  pagerSize = 20
  
canonifyURLs = true
relativeURLs = false
uglyURLs = false
enableEmoji = true
summaryLength = 70

[[menu.main]]
  name = "Trang chủ"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Bài viết"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Giới thiệu"
  url = "/about/"
  weight = 30
